name: lavoratori_stagionali
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

  cupertino_icons: ^1.0.2
  go_router: ^5.2.4
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a738913c8ce2c9f47515382d40827e794a334274
  appwrite: ^8.2.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

  appwrite_repository:
    path: packages/appwrite_repository
  person_model:
    path: packages/person_model
  authentication_repository:
    path: packages/authentication_repository
  employees_repository:
    path: packages/employees_repository
  workers_repository:
    path: packages/workers_repository
  filter:
    path: packages/filter
  json_serializable: ^6.5.4
  rxdart: ^0.27.7
  textfield_tags: ^2.0.2
  multi_select_flutter: ^4.1.3
  toggle_switch: ^2.0.1
  age_calculator: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/logo.png
      - assets/data/comuni.json
