name: workers_repository
description: Dart package which manages the workers.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  equatable: ^2.0.5
  appwrite: ^8.1.0
  person_model:
    path: ../person_model
  appwrite_api:
    path: ../appwrite_api
  rxdart: ^0.27.7

dev_dependencies:
  very_good_analysis: ^3.1.0

