name: employees_repository
description: Dart package which manages the employees.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  person_model:
    path: ../person_model

dev_dependencies:
  very_good_analysis: ^3.1.0
